// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function decodePhotos(param) {
  return Json_decode.list((function (json) {
                return /* record */[
                        /* albumId */Json_decode.field("albumId", Json_decode.$$int, json),
                        /* id */Json_decode.field("id", Json_decode.$$int, json),
                        /* title */Json_decode.field("title", Json_decode.string, json),
                        /* url */Json_decode.field("url", Json_decode.string, json),
                        /* thumbnailUrl */Json_decode.field("thumbnailUrl", Json_decode.string, json)
                      ];
              }), param);
}

exports.decodePhotos = decodePhotos;
/* No side effect */
