// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var PhotoContainer$ReactHooksTemplate = require("./PhotoContainer.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(PhotoContainer$ReactHooksTemplate.make, { }), "index");

/*  Not a pure module */
