// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as PhotoContainer$ReasonImageGridExample from "./PhotoContainer.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(PhotoContainer$ReasonImageGridExample.make, { }), "index");

export {
  
}
/*  Not a pure module */
