// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

var photoItem = Css.style(/* :: */[
      Css.height(Css.px(150)),
      /* :: */[
        Css.width(Css.px(150)),
        /* [] */0
      ]
    ]);

var container = Css.style(/* :: */[
      Css.marginLeft(Css.rem(2.0)),
      /* :: */[
        Css.marginBottom(Css.rem(2.0)),
        /* [] */0
      ]
    ]);

var Styles = {
  photoItem: photoItem,
  container: container
};

function PhotoItem(Props) {
  var photo = Props.photo;
  var photos = Props.photos;
  var setModalOpen = Props.setModalOpen;
  return React.createElement("div", {
              className: container,
              onClick: (function (param) {
                  return Curry._2(setModalOpen, photo, photos);
                })
            }, React.createElement("img", {
                  className: photoItem,
                  alt: "",
                  src: photo.url
                }));
}

var make = PhotoItem;

export {
  Styles ,
  make ,
  
}
/* photoItem Not a pure module */
