// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var photoItem = Css.style(/* :: */[
      Css.height(Css.px(150)),
      /* :: */[
        Css.width(Css.px(150)),
        /* [] */0
      ]
    ]);

var container = Css.style(/* :: */[
      Css.marginLeft(Css.rem(2.0)),
      /* :: */[
        Css.marginBottom(Css.rem(2.0)),
        /* [] */0
      ]
    ]);

var Styles = {
  photoItem: photoItem,
  container: container
};

function PhotoItem(Props) {
  var photo = Props.photo;
  var photos = Props.photos;
  var setModalOpen = Props.setModalOpen;
  return React.createElement("div", {
              className: container,
              onClick: (function (param) {
                  return Curry._2(setModalOpen, photo, photos);
                })
            }, React.createElement("img", {
                  className: photoItem,
                  alt: "",
                  src: photo.url
                }));
}

var make = PhotoItem;

exports.Styles = Styles;
exports.make = make;
/* photoItem Not a pure module */
