// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function fetchAndDecode(url, decodeFn) {
  return fetch(url).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Curry._1(decodeFn, json));
              }));
}

exports.fetchAndDecode = fetchAndDecode;
/* No side effect */
