// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Result = require("bs-platform/lib/js/belt_Result.js");

function fetchAndDecode(url, decodeFn) {
  return fetch(url).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Belt_Result.getExn(Curry._1(decodeFn, json)));
              }));
}

exports.fetchAndDecode = fetchAndDecode;
/* No side effect */
