// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var JestDom = require("bs-jest-dom/src/JestDom.bs.js");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");
var PhotoItem$ReactHooksTemplate = require("../src/PhotoItem.bs.js");

Jest.describe("PhotoItem", (function (param) {
        var photo = {
          albumId: 1,
          id: 1,
          title: "This is the title",
          url: "foo1",
          thumbnailUrl: "foo2"
        };
        var photos = /* :: */[
          photo,
          /* [] */0
        ];
        var setModalOpen = (jest.fn());
        Jest.test("renders the item", (function (param) {
                return Jest.Expect.toMatchSnapshot(Jest.Expect.expect((function (eta) {
                                    return ReactTestingLibrary.render(undefined, undefined, eta);
                                  })(React.createElement(PhotoItem$ReactHooksTemplate.make, {
                                        photo: photo,
                                        photos: photos,
                                        setModalOpen: setModalOpen
                                      })).container));
              }));
        return Jest.test("sets the src on the image", (function (param) {
                      return JestDom.toHaveAttribute("src", "foo1", Jest.Expect.expect(ReactTestingLibrary.getByAltText("", (function (eta) {
                                              return ReactTestingLibrary.render(undefined, undefined, eta);
                                            })(React.createElement(PhotoItem$ReactHooksTemplate.make, {
                                                  photo: photo,
                                                  photos: photos,
                                                  setModalOpen: setModalOpen
                                                })))));
                    }));
      }));

/*  Not a pure module */
