// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.js";
import * as React from "react";
import * as JestDom from "bs-jest-dom/src/JestDom.bs.js";
import * as ReactTestingLibrary from "bs-react-testing-library/src/ReactTestingLibrary.bs.js";
import * as PhotoModal$ReasonImageGridExample from "../src/PhotoModal.bs.js";

Jest.describe("PhotoModal", (function (param) {
        var photo = {
          albumId: 1,
          id: 1,
          title: "This is the title",
          url: "foo1",
          thumbnailUrl: "foo2"
        };
        var photos = /* :: */[
          photo,
          /* [] */0
        ];
        var onInputSubmit = (jest.fn());
        var setModalClosed = (jest.fn());
        Jest.test("renders the modal", (function (param) {
                return Jest.Expect.toMatchSnapshot(Jest.Expect.expect((function (eta) {
                                    return ReactTestingLibrary.render(undefined, undefined, eta);
                                  })(React.createElement(PhotoModal$ReasonImageGridExample.make, {
                                        photo: photo,
                                        photos: photos,
                                        setModalClosed: setModalClosed,
                                        onInputSubmit: onInputSubmit
                                      })).container));
              }));
        return Jest.test("title shows", (function (param) {
                      var partial_arg = /* `Str */[
                        4153489,
                        "This is the title"
                      ];
                      return JestDom.toBeInTheDocument(Jest.Expect.expect((function (eta) {
                                          var param = undefined;
                                          var param$1 = eta;
                                          return ReactTestingLibrary.getByText(partial_arg, param, param$1);
                                        })((function (eta) {
                                              return ReactTestingLibrary.render(undefined, undefined, eta);
                                            })(React.createElement(PhotoModal$ReasonImageGridExample.make, {
                                                  photo: photo,
                                                  photos: photos,
                                                  setModalClosed: setModalClosed,
                                                  onInputSubmit: onInputSubmit
                                                })))));
                    }));
      }));

export {
  
}
/*  Not a pure module */
